name: Build Kernel BBRv3

on:
  push:
    branches:
      - main

jobs:
  example_matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-20.04
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 16
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install git build-essential libncurses-dev libssl-dev libelf-dev bison bc flex rsync debhelper screen -y
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.8.3
        with:
          version: "16"
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Clone and configure kernel
        run: |
          git clone --branch linux-6.5.y --jobs=0 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
          cd linux
          git remote add google-bbr https://github.com/google/bbr.git
          git fetch google-bbr
          git checkout linux-6.5.y
          echo "Merge remote-tracking branch 'google-bbr/v3' into linux-6.5.y" > .git/MERGE_MSG
          git merge
      - name: Get .config
        run: ${{ steps.download_config.outputs.download_command }}
  
  download_config:
    needs: []
    runs-on: ubuntu-latest
    outputs:
      download_command: ${{ steps.get_command.outputs.download_command }}
    steps:
      - id: get_command
        run: |
          echo "::set-output name=download_command::curl -sSL https://raw.githubusercontent.com/878088/BBRv3/main/aarch64/.config > linux/.config"
  
  download_config_20_04:
    needs: []
    runs-on: ubuntu-20.04
    outputs:
      download_command: ${{ steps.get_command.outputs.download_command }}
    steps:
      - id: get_command
        run: |
          echo "::set-output name=download_command::curl -sSL https://raw.githubusercontent.com/878088/BBRv3/main/x86_64/.config > linux/.config"
