name: Build Kernel BBRv3

on:
  push:
    branches:
      - main

jobs:
  BBRv3:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 16
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install git build-essential libncurses-dev libssl-dev libelf-dev bison bc flex rsync debhelper screen -y
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.8.3
        with:
          version: "16"
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Clone and configure kernel
        run: |
          git clone --branch linux-6.5.y --jobs=0 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
          cd linux
          git remote add google-bbr https://github.com/google/bbr.git
          git fetch google-bbr
          git checkout linux-6.5.y
          echo "Merge remote-tracking branch 'google-bbr/v3' into linux-6.5.y" > .git/MERGE_MSG
          git merge
      - name: Get .config for ubuntu-latest
        if: matrix.os == 'ubuntu-latest'
        run: |
          curl -sSL https://raw.githubusercontent.com/878088/BBRv3/main/aarch64/.config > linux/.config
      - name: Get .config for ubuntu-20.04
        if: matrix.os == 'ubuntu-20.04'
        run: |
          curl -sSL https://raw.githubusercontent.com/878088/BBRv3/main/x86_64/.config > linux/.config
      - name: Print Repository Context
        run: |
          echo "Repository Owner: ${{ github.repository_owner }}"
          echo "Current Branch: ${{ github.ref }}"
          echo "Event Type: ${{ github.event_name }}"