name: Build Linux Kernel-bbrv3

on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'  
          
      - name: Checkout
        uses: actions/checkout@main
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: '18'
      
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt install git build-essential libncurses-dev libssl-dev libelf-dev bison bc flex rsync debhelper -y

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.8.3
        with:
          version: "16"

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Build
        run: bash build.sh
                                             
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: deb
          path: linux-*/*.deb
                    
      - name: Read version from Makefile
        id: version
        run: |
          export VERSION=$(grep '^VERSION =' linux/Makefile | awk -F '= ' '{print $$2}')
          export PATCHLEVEL=$(grep '^PATCHLEVEL =' linux/Makefile | awk -F '= ' '{print $$2}')
          export SUBLEVEL=$(grep '^SUBLEVEL =' linux/Makefile | awk -F '= ' '{print $$2}')
          echo "::set-output name=KERNEL_VERSION::${VERSION}.${PATCHLEVEL}.${SUBLEVEL}"
              
      - name: Release
        if: ${{ github.event.inputs.release != 'none' && github.event.inputs.release != '' }}
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "linux-*/*.deb"
          prerelease: ${{ github.event.inputs.release == 'pre-release' }}
          makeLatest: ${{ github.event.inputs.release == 'release' }}
          tag: Debian-Ubuntu-${{ steps.version.outputs.KERNEL_VERSION }}-BBRv3