name: Release

on:
  repository_dispatch:
    types:
      - release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: kernel-package

      - name: Setup Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: |
            Debian12～Ubuntu20.04
          draft: false
          prerelease: false

      - name: Upload Kernel Package
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: linux/*.deb
          asset_name: kernel.deb
          asset_content_type: application/octet-stream
