name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R
      - name: Get Latest Stable Version
        id: get_latest_version
        run: |
          version=$(curl -s https://www.kernel.org/releases.json | jq -r '.latest_stable.version')
          echo "version=$version" >> $GITHUB_ENV
      - name: Release
        if: ${{ github.event.inputs.release != 'none' }}
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "**/*.deb"
          prerelease: ${{ github.event.inputs.release == 'pre-release' }}
          makeLatest: ${{ github.event.inputs.release == 'release' }}
          tag: Debian-Ubuntu-BBRv3-${{ env.version }}
